export enum CssVariables {
  white = "var(--white)",
  black = "var(--black)",
  navigationTabBackground = "var(--navigationTabBackground)",
  activeNAvigationTabBackground = "var(--activeNAvigationTabBackground)",
  navigationTabTextColor = "var(--navigationTabTextColor)",
  lightBlue = "var(--lightBlue)",
  mildBlue = "var(--mildBlue)",
  ctaBlue = "var(--ctaBlue)",
  primary = "var(--primary)",
  paperBorderRadius = "var(--paperBorderRadius)",
  darkText = "var(--darkText)",
  error = "var(--error)",
  /**#363636 */
  dark = "var(--dark)",
  placeholderColor = "var(--placeholderColor)",
  grey = "var(--grey)",
  tint = "var(--tint)",
  lightTint = "var(--lightTint)",
  green = "var(--green)",
  mildGreen = "var(--mildGreen)",
  red = "var(--red)",
  mildRed = "var(--mildRed)",
  mildYellow = "var(--mildYellow)",
  lightGrey = "var(--lightGrey)",
  gridInputBorder = "var(--gridInputBorder)",
}
