/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface SynthetixExchangeRateInterface extends utils.Interface {
  contractName: "SynthetixExchangeRate";
  functions: {
    "acceptOwnership()": FunctionFragment;
    "addAggregator(bytes32,address)": FunctionFragment;
    "aggregatorKeys(uint256)": FunctionFragment;
    "aggregatorWarningFlags()": FunctionFragment;
    "aggregators(bytes32)": FunctionFragment;
    "anyRateIsInvalid(bytes32[])": FunctionFragment;
    "canFreezeRate(bytes32)": FunctionFragment;
    "currenciesUsingAggregator(address)": FunctionFragment;
    "currencyKeyDecimals(bytes32)": FunctionFragment;
    "currentRoundForRate(bytes32)": FunctionFragment;
    "deleteRate(bytes32)": FunctionFragment;
    "effectiveValue(bytes32,uint256,bytes32)": FunctionFragment;
    "effectiveValueAndRates(bytes32,uint256,bytes32)": FunctionFragment;
    "effectiveValueAtRound(bytes32,uint256,bytes32,uint256,uint256)": FunctionFragment;
    "freezeRate(bytes32)": FunctionFragment;
    "getCurrentRoundId(bytes32)": FunctionFragment;
    "getLastRoundIdBeforeElapsedSecs(bytes32,uint256,uint256,uint256)": FunctionFragment;
    "inversePricing(bytes32)": FunctionFragment;
    "invertedKeys(uint256)": FunctionFragment;
    "isResolverCached()": FunctionFragment;
    "lastRateUpdateTimes(bytes32)": FunctionFragment;
    "lastRateUpdateTimesForCurrencies(bytes32[])": FunctionFragment;
    "nominateNewOwner(address)": FunctionFragment;
    "nominatedOwner()": FunctionFragment;
    "oracle()": FunctionFragment;
    "owner()": FunctionFragment;
    "rateAndInvalid(bytes32)": FunctionFragment;
    "rateAndTimestampAtRound(bytes32,uint256)": FunctionFragment;
    "rateAndUpdatedTime(bytes32)": FunctionFragment;
    "rateForCurrency(bytes32)": FunctionFragment;
    "rateIsFlagged(bytes32)": FunctionFragment;
    "rateIsFrozen(bytes32)": FunctionFragment;
    "rateIsInvalid(bytes32)": FunctionFragment;
    "rateIsStale(bytes32)": FunctionFragment;
    "rateStalePeriod()": FunctionFragment;
    "ratesAndInvalidForCurrencies(bytes32[])": FunctionFragment;
    "ratesAndUpdatedTimeForCurrencyLastNRounds(bytes32,uint256)": FunctionFragment;
    "ratesForCurrencies(bytes32[])": FunctionFragment;
    "rebuildCache()": FunctionFragment;
    "removeAggregator(bytes32)": FunctionFragment;
    "removeInversePricing(bytes32)": FunctionFragment;
    "resolver()": FunctionFragment;
    "resolverAddressesRequired()": FunctionFragment;
    "roundFrozen(bytes32)": FunctionFragment;
    "setInversePricing(bytes32,uint256,uint256,uint256,bool,bool)": FunctionFragment;
    "setOracle(address)": FunctionFragment;
    "updateRates(bytes32[],uint256[],uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAggregator",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "aggregatorKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "aggregatorWarningFlags",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aggregators",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anyRateIsInvalid",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "canFreezeRate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currenciesUsingAggregator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "currencyKeyDecimals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentRoundForRate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteRate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "effectiveValue",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "effectiveValueAndRates",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "effectiveValueAtRound",
    values: [BytesLike, BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeRate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRoundId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastRoundIdBeforeElapsedSecs",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "inversePricing",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "invertedKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isResolverCached",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastRateUpdateTimes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRateUpdateTimesForCurrencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "nominateNewOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nominatedOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rateAndInvalid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateAndTimestampAtRound",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rateAndUpdatedTime",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateForCurrency",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateIsFlagged",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateIsFrozen",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateIsInvalid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateIsStale",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateStalePeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ratesAndInvalidForCurrencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "ratesAndUpdatedTimeForCurrencyLastNRounds",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ratesForCurrencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "rebuildCache",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAggregator",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeInversePricing",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "resolver", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolverAddressesRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "roundFrozen",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setInversePricing",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(functionFragment: "setOracle", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateRates",
    values: [BytesLike[], BigNumberish[], BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAggregator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aggregatorKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aggregatorWarningFlags",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aggregators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anyRateIsInvalid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canFreezeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currenciesUsingAggregator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currencyKeyDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRoundForRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "effectiveValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "effectiveValueAndRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "effectiveValueAtRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "freezeRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastRoundIdBeforeElapsedSecs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inversePricing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invertedKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isResolverCached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRateUpdateTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRateUpdateTimesForCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nominateNewOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nominatedOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rateAndInvalid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateAndTimestampAtRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateAndUpdatedTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateForCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateIsFlagged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateIsFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateIsInvalid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateIsStale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateStalePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ratesAndInvalidForCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ratesAndUpdatedTimeForCurrencyLastNRounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ratesForCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebuildCache",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAggregator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeInversePricing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolverAddressesRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roundFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInversePricing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRates",
    data: BytesLike
  ): Result;

  events: {
    "AggregatorAdded(bytes32,address)": EventFragment;
    "AggregatorRemoved(bytes32,address)": EventFragment;
    "CacheUpdated(bytes32,address)": EventFragment;
    "InversePriceConfigured(bytes32,uint256,uint256,uint256)": EventFragment;
    "InversePriceFrozen(bytes32,uint256,uint256,address)": EventFragment;
    "OracleUpdated(address)": EventFragment;
    "OwnerChanged(address,address)": EventFragment;
    "OwnerNominated(address)": EventFragment;
    "RateDeleted(bytes32)": EventFragment;
    "RatesUpdated(bytes32[],uint256[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AggregatorAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AggregatorRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CacheUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InversePriceConfigured"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InversePriceFrozen"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OracleUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerNominated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RateDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RatesUpdated"): EventFragment;
}

export type AggregatorAddedEvent = TypedEvent<
  [string, string],
  { currencyKey: string; aggregator: string }
>;

export type AggregatorAddedEventFilter = TypedEventFilter<AggregatorAddedEvent>;

export type AggregatorRemovedEvent = TypedEvent<
  [string, string],
  { currencyKey: string; aggregator: string }
>;

export type AggregatorRemovedEventFilter =
  TypedEventFilter<AggregatorRemovedEvent>;

export type CacheUpdatedEvent = TypedEvent<
  [string, string],
  { name: string; destination: string }
>;

export type CacheUpdatedEventFilter = TypedEventFilter<CacheUpdatedEvent>;

export type InversePriceConfiguredEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  {
    currencyKey: string;
    entryPoint: BigNumber;
    upperLimit: BigNumber;
    lowerLimit: BigNumber;
  }
>;

export type InversePriceConfiguredEventFilter =
  TypedEventFilter<InversePriceConfiguredEvent>;

export type InversePriceFrozenEvent = TypedEvent<
  [string, BigNumber, BigNumber, string],
  {
    currencyKey: string;
    rate: BigNumber;
    roundId: BigNumber;
    initiator: string;
  }
>;

export type InversePriceFrozenEventFilter =
  TypedEventFilter<InversePriceFrozenEvent>;

export type OracleUpdatedEvent = TypedEvent<[string], { newOracle: string }>;

export type OracleUpdatedEventFilter = TypedEventFilter<OracleUpdatedEvent>;

export type OwnerChangedEvent = TypedEvent<
  [string, string],
  { oldOwner: string; newOwner: string }
>;

export type OwnerChangedEventFilter = TypedEventFilter<OwnerChangedEvent>;

export type OwnerNominatedEvent = TypedEvent<[string], { newOwner: string }>;

export type OwnerNominatedEventFilter = TypedEventFilter<OwnerNominatedEvent>;

export type RateDeletedEvent = TypedEvent<[string], { currencyKey: string }>;

export type RateDeletedEventFilter = TypedEventFilter<RateDeletedEvent>;

export type RatesUpdatedEvent = TypedEvent<
  [string[], BigNumber[]],
  { currencyKeys: string[]; newRates: BigNumber[] }
>;

export type RatesUpdatedEventFilter = TypedEventFilter<RatesUpdatedEvent>;

export interface SynthetixExchangeRate extends BaseContract {
  contractName: "SynthetixExchangeRate";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SynthetixExchangeRateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addAggregator(
      currencyKey: BytesLike,
      aggregatorAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    aggregatorKeys(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    aggregatorWarningFlags(overrides?: CallOverrides): Promise<[string]>;

    aggregators(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    anyRateIsInvalid(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    canFreezeRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    currenciesUsingAggregator(
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<[string[]] & { currencies: string[] }>;

    currencyKeyDecimals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number]>;

    currentRoundForRate(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deleteRate(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    effectiveValue(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    effectiveValueAndRates(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        value: BigNumber;
        sourceRate: BigNumber;
        destinationRate: BigNumber;
      }
    >;

    effectiveValueAtRound(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      roundIdForSrc: BigNumberish,
      roundIdForDest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    freezeRate(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCurrentRoundId(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLastRoundIdBeforeElapsedSecs(
      currencyKey: BytesLike,
      startingRoundId: BigNumberish,
      startingTimestamp: BigNumberish,
      timediff: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    inversePricing(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, boolean, boolean] & {
        entryPoint: BigNumber;
        upperLimit: BigNumber;
        lowerLimit: BigNumber;
        frozenAtUpperLimit: boolean;
        frozenAtLowerLimit: boolean;
      }
    >;

    invertedKeys(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isResolverCached(overrides?: CallOverrides): Promise<[boolean]>;

    lastRateUpdateTimes(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    lastRateUpdateTimesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    nominateNewOwner(
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nominatedOwner(overrides?: CallOverrides): Promise<[string]>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    rateAndInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, boolean] & { rate: BigNumber; isInvalid: boolean }>;

    rateAndTimestampAtRound(
      currencyKey: BytesLike,
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

    rateAndUpdatedTime(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

    rateForCurrency(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    rateIsFlagged(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    rateIsFrozen(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    rateIsInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    rateIsStale(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    rateStalePeriod(overrides?: CallOverrides): Promise<[BigNumber]>;

    ratesAndInvalidForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], boolean] & { rates: BigNumber[]; anyRateInvalid: boolean }
    >;

    ratesAndUpdatedTimeForCurrencyLastNRounds(
      currencyKey: BytesLike,
      numRounds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & { rates: BigNumber[]; times: BigNumber[] }
    >;

    ratesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    rebuildCache(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeAggregator(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeInversePricing(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    resolver(overrides?: CallOverrides): Promise<[string]>;

    resolverAddressesRequired(
      overrides?: CallOverrides
    ): Promise<[string[]] & { addresses: string[] }>;

    roundFrozen(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setInversePricing(
      currencyKey: BytesLike,
      entryPoint: BigNumberish,
      upperLimit: BigNumberish,
      lowerLimit: BigNumberish,
      freezeAtUpperLimit: boolean,
      freezeAtLowerLimit: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOracle(
      _oracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateRates(
      currencyKeys: BytesLike[],
      newRates: BigNumberish[],
      timeSent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addAggregator(
    currencyKey: BytesLike,
    aggregatorAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  aggregatorKeys(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  aggregatorWarningFlags(overrides?: CallOverrides): Promise<string>;

  aggregators(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  anyRateIsInvalid(
    currencyKeys: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  canFreezeRate(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  currenciesUsingAggregator(
    aggregator: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  currencyKeyDecimals(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  currentRoundForRate(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deleteRate(
    currencyKey: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  effectiveValue(
    sourceCurrencyKey: BytesLike,
    sourceAmount: BigNumberish,
    destinationCurrencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  effectiveValueAndRates(
    sourceCurrencyKey: BytesLike,
    sourceAmount: BigNumberish,
    destinationCurrencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      value: BigNumber;
      sourceRate: BigNumber;
      destinationRate: BigNumber;
    }
  >;

  effectiveValueAtRound(
    sourceCurrencyKey: BytesLike,
    sourceAmount: BigNumberish,
    destinationCurrencyKey: BytesLike,
    roundIdForSrc: BigNumberish,
    roundIdForDest: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  freezeRate(
    currencyKey: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCurrentRoundId(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLastRoundIdBeforeElapsedSecs(
    currencyKey: BytesLike,
    startingRoundId: BigNumberish,
    startingTimestamp: BigNumberish,
    timediff: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  inversePricing(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, boolean, boolean] & {
      entryPoint: BigNumber;
      upperLimit: BigNumber;
      lowerLimit: BigNumber;
      frozenAtUpperLimit: boolean;
      frozenAtLowerLimit: boolean;
    }
  >;

  invertedKeys(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  isResolverCached(overrides?: CallOverrides): Promise<boolean>;

  lastRateUpdateTimes(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lastRateUpdateTimesForCurrencies(
    currencyKeys: BytesLike[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  nominateNewOwner(
    _owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nominatedOwner(overrides?: CallOverrides): Promise<string>;

  oracle(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  rateAndInvalid(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<[BigNumber, boolean] & { rate: BigNumber; isInvalid: boolean }>;

  rateAndTimestampAtRound(
    currencyKey: BytesLike,
    roundId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

  rateAndUpdatedTime(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

  rateForCurrency(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  rateIsFlagged(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  rateIsFrozen(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  rateIsInvalid(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  rateIsStale(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  rateStalePeriod(overrides?: CallOverrides): Promise<BigNumber>;

  ratesAndInvalidForCurrencies(
    currencyKeys: BytesLike[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], boolean] & { rates: BigNumber[]; anyRateInvalid: boolean }
  >;

  ratesAndUpdatedTimeForCurrencyLastNRounds(
    currencyKey: BytesLike,
    numRounds: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], BigNumber[]] & { rates: BigNumber[]; times: BigNumber[] }
  >;

  ratesForCurrencies(
    currencyKeys: BytesLike[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  rebuildCache(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeAggregator(
    currencyKey: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeInversePricing(
    currencyKey: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  resolver(overrides?: CallOverrides): Promise<string>;

  resolverAddressesRequired(overrides?: CallOverrides): Promise<string[]>;

  roundFrozen(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  setInversePricing(
    currencyKey: BytesLike,
    entryPoint: BigNumberish,
    upperLimit: BigNumberish,
    lowerLimit: BigNumberish,
    freezeAtUpperLimit: boolean,
    freezeAtLowerLimit: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOracle(
    _oracle: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateRates(
    currencyKeys: BytesLike[],
    newRates: BigNumberish[],
    timeSent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    addAggregator(
      currencyKey: BytesLike,
      aggregatorAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    aggregatorKeys(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    aggregatorWarningFlags(overrides?: CallOverrides): Promise<string>;

    aggregators(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    anyRateIsInvalid(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    canFreezeRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    currenciesUsingAggregator(
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    currencyKeyDecimals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;

    currentRoundForRate(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deleteRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    effectiveValue(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectiveValueAndRates(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        value: BigNumber;
        sourceRate: BigNumber;
        destinationRate: BigNumber;
      }
    >;

    effectiveValueAtRound(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      roundIdForSrc: BigNumberish,
      roundIdForDest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    freezeRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getCurrentRoundId(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLastRoundIdBeforeElapsedSecs(
      currencyKey: BytesLike,
      startingRoundId: BigNumberish,
      startingTimestamp: BigNumberish,
      timediff: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inversePricing(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, boolean, boolean] & {
        entryPoint: BigNumber;
        upperLimit: BigNumber;
        lowerLimit: BigNumber;
        frozenAtUpperLimit: boolean;
        frozenAtLowerLimit: boolean;
      }
    >;

    invertedKeys(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    isResolverCached(overrides?: CallOverrides): Promise<boolean>;

    lastRateUpdateTimes(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastRateUpdateTimesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    nominateNewOwner(_owner: string, overrides?: CallOverrides): Promise<void>;

    nominatedOwner(overrides?: CallOverrides): Promise<string>;

    oracle(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    rateAndInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, boolean] & { rate: BigNumber; isInvalid: boolean }>;

    rateAndTimestampAtRound(
      currencyKey: BytesLike,
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

    rateAndUpdatedTime(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

    rateForCurrency(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateIsFlagged(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rateIsFrozen(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rateIsInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rateIsStale(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rateStalePeriod(overrides?: CallOverrides): Promise<BigNumber>;

    ratesAndInvalidForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], boolean] & { rates: BigNumber[]; anyRateInvalid: boolean }
    >;

    ratesAndUpdatedTimeForCurrencyLastNRounds(
      currencyKey: BytesLike,
      numRounds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & { rates: BigNumber[]; times: BigNumber[] }
    >;

    ratesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    rebuildCache(overrides?: CallOverrides): Promise<void>;

    removeAggregator(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    removeInversePricing(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    resolver(overrides?: CallOverrides): Promise<string>;

    resolverAddressesRequired(overrides?: CallOverrides): Promise<string[]>;

    roundFrozen(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    setInversePricing(
      currencyKey: BytesLike,
      entryPoint: BigNumberish,
      upperLimit: BigNumberish,
      lowerLimit: BigNumberish,
      freezeAtUpperLimit: boolean,
      freezeAtLowerLimit: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setOracle(_oracle: string, overrides?: CallOverrides): Promise<void>;

    updateRates(
      currencyKeys: BytesLike[],
      newRates: BigNumberish[],
      timeSent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "AggregatorAdded(bytes32,address)"(
      currencyKey?: null,
      aggregator?: null
    ): AggregatorAddedEventFilter;
    AggregatorAdded(
      currencyKey?: null,
      aggregator?: null
    ): AggregatorAddedEventFilter;

    "AggregatorRemoved(bytes32,address)"(
      currencyKey?: null,
      aggregator?: null
    ): AggregatorRemovedEventFilter;
    AggregatorRemoved(
      currencyKey?: null,
      aggregator?: null
    ): AggregatorRemovedEventFilter;

    "CacheUpdated(bytes32,address)"(
      name?: null,
      destination?: null
    ): CacheUpdatedEventFilter;
    CacheUpdated(name?: null, destination?: null): CacheUpdatedEventFilter;

    "InversePriceConfigured(bytes32,uint256,uint256,uint256)"(
      currencyKey?: null,
      entryPoint?: null,
      upperLimit?: null,
      lowerLimit?: null
    ): InversePriceConfiguredEventFilter;
    InversePriceConfigured(
      currencyKey?: null,
      entryPoint?: null,
      upperLimit?: null,
      lowerLimit?: null
    ): InversePriceConfiguredEventFilter;

    "InversePriceFrozen(bytes32,uint256,uint256,address)"(
      currencyKey?: null,
      rate?: null,
      roundId?: null,
      initiator?: null
    ): InversePriceFrozenEventFilter;
    InversePriceFrozen(
      currencyKey?: null,
      rate?: null,
      roundId?: null,
      initiator?: null
    ): InversePriceFrozenEventFilter;

    "OracleUpdated(address)"(newOracle?: null): OracleUpdatedEventFilter;
    OracleUpdated(newOracle?: null): OracleUpdatedEventFilter;

    "OwnerChanged(address,address)"(
      oldOwner?: null,
      newOwner?: null
    ): OwnerChangedEventFilter;
    OwnerChanged(oldOwner?: null, newOwner?: null): OwnerChangedEventFilter;

    "OwnerNominated(address)"(newOwner?: null): OwnerNominatedEventFilter;
    OwnerNominated(newOwner?: null): OwnerNominatedEventFilter;

    "RateDeleted(bytes32)"(currencyKey?: null): RateDeletedEventFilter;
    RateDeleted(currencyKey?: null): RateDeletedEventFilter;

    "RatesUpdated(bytes32[],uint256[])"(
      currencyKeys?: null,
      newRates?: null
    ): RatesUpdatedEventFilter;
    RatesUpdated(currencyKeys?: null, newRates?: null): RatesUpdatedEventFilter;
  };

  estimateGas: {
    acceptOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addAggregator(
      currencyKey: BytesLike,
      aggregatorAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    aggregatorKeys(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    aggregatorWarningFlags(overrides?: CallOverrides): Promise<BigNumber>;

    aggregators(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    anyRateIsInvalid(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canFreezeRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currenciesUsingAggregator(
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currencyKeyDecimals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentRoundForRate(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deleteRate(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    effectiveValue(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectiveValueAndRates(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectiveValueAtRound(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      roundIdForSrc: BigNumberish,
      roundIdForDest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    freezeRate(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCurrentRoundId(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLastRoundIdBeforeElapsedSecs(
      currencyKey: BytesLike,
      startingRoundId: BigNumberish,
      startingTimestamp: BigNumberish,
      timediff: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inversePricing(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    invertedKeys(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isResolverCached(overrides?: CallOverrides): Promise<BigNumber>;

    lastRateUpdateTimes(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastRateUpdateTimesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nominateNewOwner(
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nominatedOwner(overrides?: CallOverrides): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    rateAndInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateAndTimestampAtRound(
      currencyKey: BytesLike,
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateAndUpdatedTime(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateForCurrency(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateIsFlagged(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateIsFrozen(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateIsInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateIsStale(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateStalePeriod(overrides?: CallOverrides): Promise<BigNumber>;

    ratesAndInvalidForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ratesAndUpdatedTimeForCurrencyLastNRounds(
      currencyKey: BytesLike,
      numRounds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ratesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rebuildCache(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeAggregator(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeInversePricing(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    resolver(overrides?: CallOverrides): Promise<BigNumber>;

    resolverAddressesRequired(overrides?: CallOverrides): Promise<BigNumber>;

    roundFrozen(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    setInversePricing(
      currencyKey: BytesLike,
      entryPoint: BigNumberish,
      upperLimit: BigNumberish,
      lowerLimit: BigNumberish,
      freezeAtUpperLimit: boolean,
      freezeAtLowerLimit: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOracle(
      _oracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateRates(
      currencyKeys: BytesLike[],
      newRates: BigNumberish[],
      timeSent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addAggregator(
      currencyKey: BytesLike,
      aggregatorAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    aggregatorKeys(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    aggregatorWarningFlags(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    aggregators(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    anyRateIsInvalid(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canFreezeRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currenciesUsingAggregator(
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currencyKeyDecimals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentRoundForRate(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deleteRate(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    effectiveValue(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    effectiveValueAndRates(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    effectiveValueAtRound(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      roundIdForSrc: BigNumberish,
      roundIdForDest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    freezeRate(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCurrentRoundId(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLastRoundIdBeforeElapsedSecs(
      currencyKey: BytesLike,
      startingRoundId: BigNumberish,
      startingTimestamp: BigNumberish,
      timediff: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inversePricing(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    invertedKeys(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isResolverCached(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastRateUpdateTimes(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastRateUpdateTimesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nominateNewOwner(
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nominatedOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rateAndInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateAndTimestampAtRound(
      currencyKey: BytesLike,
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateAndUpdatedTime(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateForCurrency(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateIsFlagged(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateIsFrozen(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateIsInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateIsStale(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateStalePeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ratesAndInvalidForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ratesAndUpdatedTimeForCurrencyLastNRounds(
      currencyKey: BytesLike,
      numRounds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ratesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rebuildCache(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeAggregator(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeInversePricing(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    resolver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    resolverAddressesRequired(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    roundFrozen(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setInversePricing(
      currencyKey: BytesLike,
      entryPoint: BigNumberish,
      upperLimit: BigNumberish,
      lowerLimit: BigNumberish,
      freezeAtUpperLimit: boolean,
      freezeAtLowerLimit: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOracle(
      _oracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateRates(
      currencyKeys: BytesLike[],
      newRates: BigNumberish[],
      timeSent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
