/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  SimpleBalanceOf,
  SimpleBalanceOfInterface,
} from "../SimpleBalanceOf";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class SimpleBalanceOf__factory {
  static readonly abi = _abi;
  static createInterface(): SimpleBalanceOfInterface {
    return new utils.Interface(_abi) as SimpleBalanceOfInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SimpleBalanceOf {
    return new Contract(address, _abi, signerOrProvider) as SimpleBalanceOf;
  }
}
