import ERC20_ABI from "abi/erc20.json";
import { Token, TokenSymbols } from "./containers/Swap/types";
import axialLogo from "assets/icons/logo_icon.svg"; // this needs a smaller icon logo(24)
import daiLogo from "assets/icons/dai.svg";
import fraxLogo from "assets/icons/frax.svg";
import tsdLogo from "assets/icons/tsd.svg";
import mimLogo from "assets/icons/mim.svg";
import tusdLogo from "assets/icons/tusd.svg";
import usdcLogo from "assets/icons/usdc.svg";
import usdtLogo from "assets/icons/usdt.svg";
import avaiLogo from "assets/icons/avai.svg";
import { tokenAddress } from "utils/tokenAddresses";

//symbol should be identical to key of token
export const tokens: { [K in TokenSymbols]: Token } = {
  "USDT.e": {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.USDTe),
    symbol: "USDT.e",
    name: "Tether",
    geckoId: "tether",
    logo: usdtLogo,
    decimals: 6,
    masterchefId: 0,
    isSynthetic: false,
    isLPToken: false,
  },
  usdcAM3DUSD: {
    address: tokenAddress(TokenSymbols.usdcAM3DUSD),
    ABI: ERC20_ABI,
    decimals: 18,
    symbol: "usdcAM3DUSD",
    name: "Axial USDC/AM3D",
    logo: axialLogo,
    geckoId: "usdcam3dusd",
    masterchefId: 5,
    isSynthetic: false,
    isLPToken: true,
  },
  ac4dUSD: {
    address: tokenAddress(TokenSymbols.ac4dUSD),
    ABI: ERC20_ABI,
    decimals: 18,
    symbol: "ac4dUSD",
    name: "AC4D TSD/MIM/FRAX/DAI.e",
    logo: axialLogo,
    geckoId: "ac4dusd",
    masterchefId: 1,
    isSynthetic: false,
    isLPToken: true,
  },
  aa3dUSD: {
    address: tokenAddress(TokenSymbols.aa3dUSD),
    ABI: ERC20_ABI,
    decimals: 18,
    symbol: "aa3dUSD",
    name: "AA3D AVAI/MIM/USDC.e",
    logo: axialLogo,
    geckoId: "aa3dusd",
    masterchefId: 4,
    isSynthetic: false,
    isLPToken: true,
  },
  am3dUSD: {
    address: tokenAddress(TokenSymbols.am3dUSD),
    ABI: ERC20_ABI,
    decimals: 18,
    symbol: "am3dUSD",
    name: "AM3D MIM/USDC.e/DAI.e",
    logo: axialLogo,
    geckoId: "am3dusd",
    masterchefId: 3,
    isSynthetic: false,
    isLPToken: true,
  },
  as4dUSD: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.as4dUSD),
    decimals: 18,
    symbol: "as4dUSD",
    name: "AS4D DAI.e/USDC.e/USDT.e/TUSD",
    geckoId: "as4dusd",
    masterchefId: 0,
    isSynthetic: false,
    isLPToken: true,
    logo: axialLogo,
  },
  JLP: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.JLP),
    decimals: 18,
    symbol: "JLP",
    name: "JLP",
    geckoId: "jlpavaxaxial",
    logo: axialLogo,
    masterchefId: 2,
    isSynthetic: false,
    isLPToken: true,
  },
  FRAX: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.FRAX),
    decimals: 18,
    symbol: "FRAX",
    name: "Frax",
    logo: fraxLogo,
    geckoId: "frax",
    masterchefId: 0,
    isSynthetic: false,
    isLPToken: false,
  },
  FXS: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.FXS),
    decimals: 18,
    symbol: "FXS",
    name: "Frax Share",
    logo: axialLogo,
    geckoId: "frax-share",
    isLPToken: false,
    isSynthetic: false,
    masterchefId: 0,
  },
  "DAI.e": {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.DAI),
    decimals: 18,
    symbol: "DAI.e",
    logo: daiLogo,
    geckoId: "dai",
    name: "Dai",
    masterchefId: 0,
    isSynthetic: false,
    isLPToken: false,
  },
  AVAI: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.AVAI),
    decimals: 18,
    symbol: "AVAI",
    logo: avaiLogo,
    geckoId: "orca-avai",
    name: "Orca AVAI",
    masterchefId: 0,
    isSynthetic: false,
    isLPToken: false,
  },
  TSD: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.TSD),
    decimals: 18,
    symbol: "TSD",
    name: "Teddy Dollar",
    logo: tsdLogo,
    geckoId: "teddy-dollar",
    masterchefId: 0,
    isSynthetic: false,
    isLPToken: false,
  },
  USDC: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.USDC),
    decimals: 6,
    symbol: "USDC",
    name: "Native USDC",
    logo: usdcLogo,
    geckoId: "usd-coin",
    masterchefId: 0,
    isSynthetic: false,
    isLPToken: false,
  },
  MIM: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.MIM),
    decimals: 18,
    symbol: "MIM",
    name: "Magic Internet Money",
    logo: mimLogo,
    geckoId: "magic-internet-money",
    masterchefId: 0,
    isSynthetic: false,
    isLPToken: false,
  },
  TEDDY: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.TEDDY),
    decimals: 18,
    symbol: "TEDDY",
    name: "Teddy",
    logo: axialLogo,
    geckoId: "teddy",
    isLPToken: false,
    isSynthetic: false,
    masterchefId: 0,
  },
  WAVAX: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.WAVAX),
    decimals: 18,
    symbol: "WAVAX",
    name: "Wrapped AVAX",
    logo: axialLogo,
    geckoId: "avalanche-2",
    isLPToken: false,
    isSynthetic: false,
    masterchefId: 0,
  },
  TUSD: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.TUSD),
    decimals: 18,
    symbol: "TUSD",
    name: "TUSD",
    logo: tusdLogo,
    geckoId: "true-usd",
    masterchefId: 0,
    isSynthetic: false,
    isLPToken: false,
  },
  "USDC.e": {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.USDCe),
    decimals: 6,
    symbol: "USDC.e",
    name: "USDC.e",
    logo: usdcLogo,
    geckoId: "usd-coin",
    isLPToken: false,
    isSynthetic: false,
    masterchefId: 0,
  },
  ORCA: {
    ABI: ERC20_ABI,
    address: tokenAddress(TokenSymbols.ORCA),
    decimals: 18,
    symbol: "ORCA",
    name: "Orca DAO",
    logo: axialLogo,
    geckoId: "orcadao",
    masterchefId: 0,
    isSynthetic: false,
    isLPToken: false,
  },
};
export const extraRewardTokens = [
  tokens.TEDDY,
  tokens.FXS,
  tokens.WAVAX,
  tokens.ORCA,
];
