#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run checkFormat ||
(
    echo '
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)


# Check ESLint Standards
npm run checkEslint ||
(
        echo '
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run checkTs ||
(
    echo '
            type check failed! Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
# echo 'all checks have passed'

# If everything passes... Now we can commit
echo '✅✅✅✅  committing  ✅✅✅✅'
