AWS_PROFILE=snowball
export AWS_PROFILE

init:
	terraform init
plan:
	terraform plan
show:
	terraform show
apply:
	terraform apply
destroy:
	terraform destroy
push-error:
	terraform state push errored.tfstate