#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Prettier standards
npm run checkFormat ||
(
    echo 'bad styling!
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# # Check ESLint Standards
# npm run checkEslint ||
# (
#         echo 'lint check failed!
#                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
#         false; 
# )

# TODO : I disabled checkTs(reduce spend time) until we recreate skeleton.  
# Check tsconfig standards
npm run checkTs ||
(
    echo 'checking types failed!
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '  Trying to build now.'

npm run build ||
(
    echo ' build failed ❌
            CRA build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ committing. ✅✅✅✅'
