#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# echo '🏗️👷 Styling, testing and building your project before committing'

# TODO : please uncomment this and then commit. I needed to commit & create MR without formatting code! 
# Check Prettier standards
npm run checkFormat ||
(
    echo '🤢🤮🤢🤮 Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# TODO : I disabled checkEslint(reduce spend time) until we recreate skeleton. 
# Check ESLint Standards
# npm run check-lint ||
# (
#         echo '😤🏀👋😤 Get that weak code out of here! 😤🏀👋😤 
#                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
#         false; 
# )

# TODO : I disabled checkTs(reduce spend time) until we recreate skeleton.  
# Check tsconfig standards
# npm run check-types ||
# (
#     echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
#             Are you seriously trying to write that? Make the changes required above.'
#     false;
# )

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# npm run build ||
# (
#     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#             CRA build failed: View the errors above to see why. 
#     '
#     false;
# )

# If everything passes... Now we can commit
echo '✅✅✅✅ committing. ✅✅✅✅'
