name: Dev env deployment
on:
  push:
    branches:
    - v2
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://dev-app.axial.exchange
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.1
    - name: Install
      run: |
        npm install
    - name: Build
      run: |
        npm run build
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Upload to s3 and invalidate cache
      run: | 
        aws s3 cp --recursive build/ s3://${{secrets.DEV_S3_BUCKET}}
        aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_DISTRIBUTION_ID }} --paths "/*"
