name: Dev env deployment
on:
  push:
    branches:
    - develop
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://dev-app.axial.exchage
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.1
    - name: Install
      run: |
        npm install
    - name: Build
      run: |
        npm run build
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy branch to S3 bucket
      run: | 
        aws s3 cp --recursive build/ s3://${{secrets.DEV_S3_BUCKET}}
        aws cloudfront create-invalidation --distribution-id ${{ DEV_DISTRIBUTION_ID }} --paths "/*"

name: Prod env deployment
on:
  push:
    branches:
    - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://app.axial.exchage
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.1
    - name: Install
      run: |
        npm install
    - name: Build
      run: |
        npm run build
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy branch to S3 bucket
      run: | 
        aws s3 cp --recursive build/ s3://${{secrets.S3_BUCKET}}
        aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
