on: pull_request

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 14
        
    - name: Build
      run: |
        npm run build

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy branch to S3 bucket
      run: aws s3 cp --recursive build/ s3://${{secrets.DEV_S3_BUCKET}}/${{steps.extract_branch.branch}}
  
  display-link:
    runs-on: ubuntu-latest
    name: Comment link to deployed pr
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        
        with:
          message: 'This PR is automatically being deployed to https://preview-${{steps.extract_branch.branch}}.dev-app.axial.exchange'
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}